### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by rpodcast** [rpodcast/shinybrain#18]
`shinylearning` is likely not the final name of this package. Here are some other suggestions:
* `shinysnapshot`
* Play on the concept of time machine

**Comment by PythonCoderUnicorn** [comment]
`shinylearning` renaming options:

- [ ] shinybrain
- [ ] shinytree
- [ ] shinygem
- [ ] shinydesk
- [ ] shinyl
- [ ] shinywhale
- [ ] shinydevil
- [ ] simplyshiny
- [ ] shinybox
- [ ] shinyhomework
- [ ] ladybug
- [ ] shinymobius
- [ ] shinynautulus 
- [ ] shinypupil 
- [ ] shinyR
- [ ] shinyapple

**Comment by rpodcast** [comment]
Great suggestions, @PythonCoderUnicorn! Keeping with the teaching/education purpose of the package, I'm leaning towards these options from your list:
* shinyapple (hopefully it doesn't make the reader think of Apple the company)
* shinypupil (or perhaps shinystudent)
* shinybrain (great opportunity for a cool logo)

**Comment by PythonCoderUnicorn** [comment]
Here is a logo design for shinybrain, stuck with blue as that is the color of choice for you/ brand

![Screen Shot 2022-03-05 at 9 29 40 AM](https://user-images.githubusercontent.com/55933131/156891916-3538ce47-9a8f-4c4e-901f-d928cb92a8e4.png)

**Comment by rpodcast** [comment]
It is official, the package will be named **shinybrain**!

**Comment by PythonCoderUnicorn** [comment]
full size 

![shinybrain (1)](https://user-images.githubusercontent.com/55933131/158830162-7d0148cc-1839-410b-9b62-2b89471aa507.png)

**Comment by rpodcast** [comment]
It is now __shinybrain__!
